# Generated by Django 2.2.12 on 2020-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='videos/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='videos/covers/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
