# Generated by Django 2.2.12 on 2020-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200507_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='video',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='videos/video/'),
            preserve_default=False,
        ),
    ]
