# Generated by Django 2.2.12 on 2020-05-08 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1, verbose_name='Id')),
                ('ubicacion', models.CharField(default='-', max_length=200, verbose_name='Ubicacion')),
                ('nombre_sucursal', models.CharField(default='-', max_length=200, verbose_name='Nombre sucursal')),
                ('localidad_sucursal', models.CharField(default='-', max_length=200, verbose_name='Localidad sucursal')),
                ('licencia', models.CharField(default='-', max_length=200, verbose_name='Licencia')),
                ('modo_operacion', models.CharField(choices=[('EN RED', 'EN RED'), ('EN LOCAL', 'EN LOCAL'), ('STAND ALONE', 'STAND ALONE')], default='EN RED', max_length=50, verbose_name='Modo operacion')),
                ('numero_serie', models.CharField(default='-', max_length=200, verbose_name='Numero de serie')),
                ('politicas', models.TextField(default='-', max_length=200, verbose_name='Politicas')),
                ('tolerancia', models.IntegerField(default=0, verbose_name='Tolerancia')),
                ('version_app', models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Costo')),
                ('sincronizado_al_servidor', models.BooleanField(verbose_name='Sincronizado al servidor')),
                ('tipo', models.CharField(choices=[('Expedidor', 'Expedidor'), ('Validador', 'Validador'), ('Cajero', 'Cajero'), ('Punto de cobro', 'Punto de cobro'), ('Servidor', 'Servidor')], default='Expedidor', max_length=50, verbose_name='Tipo')),
                ('actualizacion_automatica', models.BooleanField(verbose_name='Actualizacion automatica')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('id_sucursal', models.IntegerField(verbose_name='Sucursal')),
                ('id_impresora', models.IntegerField(verbose_name='Imprsora')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_base', models.IntegerField(default=2, verbose_name='Tiempo base')),
                ('monto_base', models.IntegerField(default=5, verbose_name='Monto base')),
                ('fraccion_tiempo', models.IntegerField(default=0, verbose_name='Fraccion de tiempo')),
                ('incremental', models.IntegerField(default=0, verbose_name='Incremental')),
                ('descuento', models.IntegerField(default=0, verbose_name='Descuento')),
                ('prioridad', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('fecha_inicio', models.TimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.TimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horario inicio')),
                ('horario_fin', models.TimeField(blank=True, null=True, verbose_name='Horario fin')),
                ('dia_semana', models.CharField(blank=True, choices=[('ninguno', 'ninugno'), ('lunes', 'lunes'), ('martes', 'MARTES'), ('miercoles', 'miercoles'), ('jueves', 'jueves'), ('viernes', 'viernes'), ('sabado', 'sabado'), ('domingo', 'domingo')], max_length=200, null=True, verbose_name='Dia de la semana')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('updated', models.DateField(auto_now=True, verbose_name='Ultima modificacion')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_tarifa', to='equipo.Equipo', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifa',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(default='-', max_length=200, verbose_name='Numero de serie')),
                ('modelo', models.CharField(choices=[('TUP', 'TUP'), ('Epson', 'Epson'), ('Eltra', 'Eltra'), ('Otro', 'Otro')], default='-', max_length=200, verbose_name='Modelo')),
                ('direccion', models.CharField(default='-', max_length=200, verbose_name='direccion')),
                ('tipo', models.CharField(choices=[('Rollo', 'Rollo'), ('Fanfold', 'Fanfold'), ('Pvc', 'Pvc')], default='Rollo', max_length=50, verbose_name='Tipo')),
                ('ancho_papel', models.IntegerField(default=80, verbose_name='Ancho de papel')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_impresora', to='equipo.Equipo', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresora',
                'ordering': ['-modelo'],
            },
        ),
    ]
