# Generated by Django 2.2.12 on 2020-05-08 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_boleto', models.IntegerField(verbose_name='Folio boleto')),
                ('expedidor_boleto', models.IntegerField(verbose_name='Expedidor boleto')),
                ('fecha_expedicion_boleto', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de expedicion boleto')),
                ('codigo', models.IntegerField(verbose_name='Codigo')),
                ('registrado', models.BooleanField(verbose_name='Registrado')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('cambio', models.IntegerField(verbose_name='Cambio')),
                ('monedas', models.CharField(max_length=200, verbose_name='Monedas')),
                ('billetes', models.CharField(max_length=200, verbose_name='Billetes')),
                ('cambio_entregado', models.CharField(max_length=200, verbose_name='Cambio entregado')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha transaccion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_transaccion', to='equipo.Equipo', verbose_name='Equipos')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transaccion',
                'ordering': ['-created'],
            },
        ),
    ]
