# Generated by Django 2.2.12 on 2021-08-05 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
        ('transaccion', '0002_auto_20210802_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='det_estacionamiento',
            field=models.CharField(max_length=200, verbose_name='Determinante estacionamiento'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='equipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_transaccion', to='equipo.Equipo', verbose_name='Equipo'),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_boleto', models.IntegerField(verbose_name='Folio boleto')),
                ('entrada', models.IntegerField(verbose_name='Numero de entrada')),
                ('fecha_expedicion_boleto', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de expedicion boleto')),
                ('codigo', models.IntegerField(verbose_name='Codigo de registro')),
                ('registrado', models.BooleanField(verbose_name='Registrado')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_boleto', to='equipo.Equipo', verbose_name='Equipo')),
                ('tienda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_boleto', to='transaccion.Tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boleto',
                'ordering': ['-created'],
            },
        ),
    ]
