# Generated by Django 2.2.12 on 2021-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_auto_20210805_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='folio_boleto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folio boleto'),
        ),
    ]
