# Generated by Django 2.2.12 on 2021-08-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0004_auto_20210805_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='folio_boleto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_transaccion', to='transaccion.Boleto', verbose_name='Folio boleto'),
        ),
    ]
