# Generated by Django 2.2.12 on 2021-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0005_auto_20210805_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='registrado',
            field=models.BooleanField(default=True, verbose_name='Registrado'),
        ),
    ]
