# Generated by Django 2.2.12 on 2021-08-06 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0006_auto_20210805_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_expedicion_boleto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
    ]
