# Generated by Django 2.2.12 on 2020-05-08 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DATOS', 'DATOS'), ('MEDIA', 'MEDIA'), ('API', 'API')], default='DATOS', max_length=50, verbose_name='Tipo')),
                ('direccion', models.CharField(default='-', max_length=200, verbose_name='Direccion')),
                ('puerto', models.CharField(blank=True, default='23', max_length=200, null=True, verbose_name='Puerto')),
                ('access_token', models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='Token')),
                ('medio', models.CharField(choices=[('LAN', 'LAN'), ('WEB', 'WEB'), ('ALMACENAMIENTO INTERNO', 'ALMACENAMIENTO INTERNO'), ('ALMACENAMIENTO EXTERNO', 'ALMACENAMIENTO EXTERNO')], default='LAN', max_length=200, verbose_name='Medio')),
                ('modo_operacion', models.CharField(choices=[('EN ESPERA', 'EN ESPERA'), ('CONTINUO', 'CONTINUO'), ('MONITOR', 'MONITOR')], default='EN ESPERA', max_length=50, verbose_name='Modo operacion')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_servidor', to='equipo.Equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidor',
                'ordering': ['-direccion'],
            },
        ),
    ]
