# Generated by Django 2.2.12 on 2020-05-08 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controladora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=200, verbose_name='Nombre')),
                ('numero', models.IntegerField(default=1, verbose_name='Id')),
                ('numero_serie', models.CharField(default='-', max_length=200, verbose_name='Numero de serie')),
                ('tipo', models.CharField(choices=[('VALIDADOR', 'VALIDADOR'), ('DISPENSADOR', 'DISPENSADOR'), ('RECICLADOR', 'RECICLADOR'), ('LECTOR', 'LECTOR')], default='Controladora Arduino', max_length=50, verbose_name='Tipo')),
                ('direccion', models.CharField(default='-', max_length=200, verbose_name='Direccion')),
                ('puerto', models.CharField(choices=[('COM', 'COM'), ('USB', 'USB')], default='23', max_length=200, verbose_name='Puerto')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('controladora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_dispositivo', to='controladora.Controladora', verbose_name='Controladora')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivo',
                'ordering': ['-nombre'],
            },
        ),
    ]
