# Generated by Django 2.2.12 on 2020-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['-numero'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivo'},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='capacidades',
            field=models.CharField(default='-', max_length=200, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='denominaciones',
            field=models.CharField(default='-', max_length=200, verbose_name='Denominaciones'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='Prioridad'),
        ),
    ]
