# Generated by Django 2.2.12 on 2020-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_auto_20200525_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='capacidades',
            field=models.CharField(default='-', help_text="Indica la capacidad maxima en el orden de las denominaciones  separada por ':' Ejemplo: 200:250:200", max_length=200, verbose_name='Capacidad maxima por denominacion'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='denominaciones',
            field=models.CharField(default='-', help_text="Indica las denominaciones aceptadas.separadas por ':' Ejemplo: 1000:500:200", max_length=200, verbose_name='Denominaciones aceptadas'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='numero',
            field=models.IntegerField(default=1, help_text='Prioridad respecto a los demas dispositivos', verbose_name='Prioridad'),
        ),
    ]
